### ISSUE TITLE
Real space and Fourier space sampling

### ISSUE THREAD

**Issue by roflmaostc** [ebezzam/waveprop#6]
I leave it as an issue for discussion here:

Let's say we have a detector with 4 Pixels and a length of 1.
Do you specify the real space positions of the pixels as: 0, 0.25, 0.5, 0.75?
Or would you go with: 0, 0.333, 0.666, 1.0

I prefer actually the first version, because of several reasons:

* the points indicate the midpoints of the pixels. The boundary of the outer pixels make up for the missing "0.25".
* In Fourier optics we interpret the signal as a discrete sample of the ground truth continuous one. Hence, if Nyquist is fulfilled, the samples of the detector describe the Fourier series fully. If we would interpolate it to 10 pixels, the real space points would be then [0, 0.125, 0.250, 0.375,..., 0.75, 0.8725].

Which one did you choose in the library here?

In Fourier space, I always use `fftfreq` and in real-space I always use [fftpos](https://nanoimaging.de/FourierTools.jl/dev/helpers/#FourierTools.fftpos).

**Comment by roflmaostc** [comment]
Is there any news on it :D?
@ebezzam

**Comment by ebezzam** [comment]
So [this](https://github.com/ebezzam/waveprop/blob/c07863aac87a8cd9f90ad43aa8428eb185c1595b/waveprop/util.py#L110) is how it's done in spatial domain, and [this](https://github.com/ebezzam/waveprop/blob/c07863aac87a8cd9f90ad43aa8428eb185c1595b/waveprop/rs.py#L546) for frequency domain.

I think it's not really either version you mention? as the user is asked to specify the sampling rate. Which I think it more appropriate because with sensors/SLMs we may want to replicate their pitch / sampling rate. What do you think?

**Comment by roflmaostc** [comment]
The frequencies look good, since it matches with FFTWs `fftfreq`.
and real space looks good, too?
It's not symmetric for even numbers, right? (And I think that is what you want to have :D)

**Comment by ebezzam** [comment]
Yep, it's not symmetric for even numbers. For `N ` even, `np.arange(-N/2, N/2)` will range from `[-N/2, N/2-1]`
